### PR TITLE
Fix secondary sidebar display of class attributes

### LINKED ISSUE #785: Readthedocs: long attributes aren't fully displayed in secondary sidebar
Longer attributes are not displayed fully in secondary sidebar.
Example: 

Image

<br>
We could display just the attribute names per class e.g. `T`, `cdim` etc.

Example: 
Image

### PR DESCRIPTION
**Pull request by hoyer-a**
Closes #785 

Adjust display of secondary sidebar using custom js.
Show only class `attribute` in sidebar instead of `class.attribute`.

### CODE REVIEW

**Comment by mberz** [comment]
I realized that the width of the right hand sidebar is still quite narrow. Maybe we can also increase the width of that a bit more or is this scaled automatically?

**Comment by mberz** [comment]
Ah, that's too bad. I was hoping it would make the page a bit wider.

File: docs/_static/custom.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+    const sidebarToc = document.querySelector(".bd-sidebar-secondary");
+    if (!sidebarToc) return;
+
+    // Select spans only inside <li class="toc-h3 nav-item toc-entry">
+    const tocSpans = sidebarToc.querySelectorAll("li.toc-h3.nav-item.toc-entry .pre");
+
+    tocSpans.forEach(span => {
+        const original = span.textContent;
+        if (original.includes(".")) {
+            span.textContent = original.split(".").pop(); // Keep only what comes after the last dot
```
Comment (f-brinkmann) [inline docs/_static/custom.js:12]: Wouldn't it be safer to keep everything after the first dot? Otherwise information for nested classes would not be displayed correctly. E.g., if we had something like 'Signal.Coordinates.elevation' it would only display 'elevation'.

**Review by f-brinkmann — CHANGES_REQUESTED** [review]
Had only a small question. Docs look way better and cleaner than before :)

File: docs/_static/custom.js (hunk 1 above)
Comment (hoyer-a) [reply docs/_static/custom.js:12]: Yes, definitely! Did not think of that.

**Comment by hoyer-a** [comment]
Not sure why the test failed, had no problems locally. Can someone maybe restart it on circleci?

**Comment by f-brinkmann** [comment]
> Not sure why the test failed, had no problems locally. Can someone maybe restart it on circleci?

I think only @mberz has the power to do that 🙈

**Comment by mberz** [comment]
> > Not sure why the test failed, had no problems locally. Can someone maybe restart it on circleci?
> 
> I think only @mberz has the power to do that 🙈

Theoretically everyone who is part of the pyfar organization should be able to rerun tests. You need to be logged in though.

File: docs/_static/custom.js [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+
+    // Select spans only inside <li class="toc-h3 nav-item toc-entry">
+    const tocSpans = sidebarToc.querySelectorAll("li.toc-h3.nav-item.toc-entry .pre");
+
+    tocSpans.forEach(span => {
+        const original = span.textContent;
+        const firstDotIndex = original.indexOf(".");
+        span.textContent = original.slice(firstDotIndex + 1); // Keep everything after the first dot
+    });
+});
```
Comment (mberz) [inline docs/_static/custom.js:14]: Could you please a bit of documentation what this function does. 
Otherwise this piece of information may be forgotten in the future ;)

**Review by mberz — COMMENTED** [review]
Please add some documentation, otherwise all good.

**Review by ahms5 — APPROVED** [review]
